name: Cocoapods

on: [push]

jobs:
  GlossButtonNode:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: "13.4"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods
        run: pod lib lint --allow-warnings GlossButtonNode.podspec
